---
title: "Talks & Publications"
output: html_document
---

## Talks

Below is a current list of conferences at which I have presented, or will present, some of my work with J&J.

1. [Women in Statistics and Data Science](http://ww2.amstat.org/meetings/wsds/2018/onlineprogram/AbstractDetails.cfm?AbstractID=304956) | October 18-20 2018 | Cincinnati, OH  | [Poster](presentations/Eltinge WSDS Poster.pdf)
2. [EARL Conference Boston](https://earlconf.com/2018/boston/) | November 13 2018 | Boston, MA | [Slides](presentations/Eltinge JnJ EARL 2018.pdf)
3. [rstudio::conf](https://www.rstudio.com/conference/) | January 17-18 2019 | Austin, TX

Last updated 10/27/18.

## Publications

I have been published twice for addiction treatment work I completed as an undergraduate student at Brown University:

1. Haass-Koffler, Carolina L., Kimberly Goodyear, William H. Zywiak, Molly Magill, Sarah E. Eltinge, Paul M. Wallace, Victoria M. Long et al. "Higher pretreatment blood pressure is associated with greater alcohol drinking reduction in alcohol-dependent individuals treated with doxazosin." Drug & Alcohol Dependence 177 (2017): 23-28. [link](https://www.drugandalcoholdependence.com/article/S0376-8716(17)30200-4/fulltext)

2. Parker, Donna R., Sarah Eltinge, Caitlin Rafferty, Charles B. Eaton, Jennifer G. Clarke, and Roberta E. Goldman. "Primary Care Providers’ Views on Using Lung Age as an Aid to Smoking Cessation Counseling for Patients with Chronic Obstructive Pulmonary Disease." Lung 193, no. 3 (2015): 321-327. [link](https://link.springer.com/article/10.1007/s00408-015-9708-8)